### ISSUE TITLE
Add Ability to Specify Crafting Amount

### ISSUE THREAD

**Issue by Patar221** [JustinO1055/Erovar-Adventure#3]
Add the ability for a play to specify how many items they would like to craft for a given recipe in the "adv craft" command.
Also add ability to use suffixes such as "100k" for 100 000 or "1m" for 1 000 000 000.

**Comment by JustinO1055** [comment]
Completed adding support for crafting multiple at once. Need to test some more.

Need to implement error checking for returning -1 (invalid number) from parse function

**Comment by JustinO1055** [comment]
Error in. Appears to work. Closing.
